print ("Hello! Please set values for integers ")
a=int(input("Please set value for a \n"))
b=int(input("Please set value for b \n"))
summ=(a+b)
difference=(a-b)
multiply =(a*b)
divide =(a/b)
print ("a+b=", summ)
print ("a-b=", difference)
print ("a*b=", multiply)
print ("a/b=", divide)